name: oppkey-theta-atk-flutter
version: 0.0.1
summary: RICOH THETA API Test Kit Demonstration
description: Demonstration of theta and thetaf packages for RICOH THETA WebAPI.  From community member Oppkey.

confinement: strict
base: core18
grade: stable

slots:
  dbus-oppkey-theta-atk-flutter: # adjust accordingly to your app name
    interface: dbus
    bus: session
    name: com.oppkey.thetax_mjpeg # adjust accordingly to your app name and
    
apps:
  oppkey-theta-atk-flutter:
    command: thetax_mjpeg
    extensions: [flutter-stable] # Where "master" defines which Flutter channel to use for the build
    plugs:
    - network
    slots:
      - dbus-oppkey-theta-atk-flutter
parts:
  oppkey-theta-atk-flutter:
    source: .
    plugin: flutter
    flutter-target: lib/main.dart # The main entry-point file of the application
